### ISSUE TITLE
Allow to use streams

### ISSUE THREAD

**Issue by piranna** [perry-mitchell/webdav-fs#21]
Allow to fetch and upload data using streams instead of requiring to download or upload the content on a single operation.

**Comment by perry-mitchell** [comment]
Is this the same as #27 ?

**Comment by piranna** [comment]
No, this is about use internally the Streams API.

**Comment by ultimate-tester** [comment]
I can't see how this is not the same as #23.. Could you please provide some sample code of what you would like to achieve so I can see what I can do about it?

**Comment by perry-mitchell** [comment]
If nothing else @ultimate-tester I guess this could be seen as the next step to the code you provided (using real streams straight from the source rather than get and convert to a stream.

@piranna if this is still not on point perhaps a further clarification could be handy. If we at least patch this process so we get some kind of API going first, and then opt to use streams end-to-end later, we'll be in a better place sooner imo.

**Comment by piranna** [comment]
> If nothing else @ultimate-tester I guess this could be seen as the next step to the code you provided (using real streams straight from the source rather than get and convert to a stream.

Mostly yes :-) @ultimate-tester pull-request provides (part of) the streams API, but internally it's fetching the full file at once, so there's no diference with the non-stream APIs. What I'm asking on this issue is that `webdav-fs` (and/or `webdav-client`, too) uses the streams API internally too, ideally also in the case the file is later provided with the non-stream API too.


> If we at least patch this process so we get some kind of API going first, and then opt to use streams end-to-end later, we'll be in a better place sooner imo.

Ok, I agree, we could have first the public API and later move to use streams end-to-end, although I think it's easier to do it otherwise (first streams end-to-end, and later offer the API).

**Comment by perry-mitchell** [comment]
Ok.. so I guess we're moving on this sooner rather than later. I can take a crack at the writing for now.. even if it's very rudimentary. I'm still very confused as to the difference between this issue @piranna and #23.. I feel that they're the same issue. **webdav-client** should have an identical task (I believe it does), but I'm not sure what else would be needed other than stream support end to end (read + write, proper streams).

**Comment by ultimate-tester** [comment]
This is very easily fixable. The current code I provided uses the option start and end to provide a range of data instead of the full file at once (as per HTTP protocol). What NodeJS does with a "real" streaming API is providing 40 KB (from head, could be something else) instead of the full file. I only need to modify the code so that when no end is provided, it will take start + 40KB or the actual EOF. Then it will fully "emulate" the streaming API, but the 'open' and 'close' events will fire for each part rather than one file, not sure if that matters too much though..

**Comment by piranna** [comment]
Seems to me to be a bit hackish... I would go for real streams all the way
down.

**Comment by perry-mitchell** [comment]
This has been present for some time, so I'm closing this issue. Ranges on write streams are not available due to their questionable support. I'm open to having a PR made for them, however.

**Comment by piranna** [comment]
> Ranges on write streams are not available due to their questionable support.

Maybe an `OPTIONS` request would provide info about their support?

**Comment by perry-mitchell** [comment]
> Maybe an OPTIONS request would provide info about their support?

I meant that I hadn't added it due to the lack of support that *servers* have for writing ranges - but I'm definitely OK with someone contributing support for ranged write streams. I just don't have a server up my sleeve to test such functionality with.

I'd have also wanted it to be supported within the testing environment, but that webdav server doesn't support ranged writes, so that makes testing difficult.

**Comment by piranna** [comment]
> Maybe an OPTIONS request would provide info about their support?
> I meant that I hadn't added it due to the lack of support that servers have for writing ranges - but I'm definitely OK with someone contributing support for ranged write streams. I just don't have a server up my sleeve to test such functionality with.

Fair enough, not being standard makes sense you would not provide support for it, at least on the core source code... Unluckily there's no official standard for it, and in fact, the "oficial" standard dictates to don't use ranged `PUT`, that this would have been the easiest solution... :-(


> I'd have also wanted it to be supported within the testing environment, but that webdav server doesn't support ranged writes, so that makes testing difficult.

I think my server [Davius](https://github.com/piranna/Davius) supports it...
