### ISSUE TITLE
webdav-fs and OwnCloud

### ISSUE THREAD

**Issue by houssem-yahiaoui** [perry-mitchell/webdav-fs#27]
I have this problem when i tried to use the module with owncloud webdav i got this 401 bad response that i didn't knew how to interpret.

is it compatible with owncloud, and how we can make it happen.

**Comment by perry-mitchell** [comment]
I've sent you an email to follow up.

**Comment by kidandcat** [comment]
I have the same problem, there is any solution?

**Comment by perry-mitchell** [comment]
What URL are you requesting with WebDAV? Perhaps you could paste a code sample here, with your domain and credible obfuscated of course.

**Comment by kidandcat** [comment]
I got it worked, I was listing the directory and then Stating each file, owncloud webdav was failing due to high speed Stat requests, I fixed it with the pull request, so I get all the directory data in just one propfind request now, that's the way other webdav clients do it. So now it is not necessary to stat all files in a directory to get their information.

**Comment by perry-mitchell** [comment]
This has been resolved, and patched in #29

**Comment by nonoyek** [comment]
Hi i am having problem in reading photo file using webdav-fs. Only '.txt' file is accepted, any solution?

**Comment by perry-mitchell** [comment]
@nonoyek You can use `readFile` to return binary data (Buffer):

```javascript
client.readFile("/pic.jpg", "binary", (err, data) => {
  // data is a Buffer
});
```

**Comment by perry-mitchell** [comment]
Updated the docs for [`readFile`](https://github.com/perry-mitchell/webdav-fs#readfilepath-encoding-callback) in the readme.
