### ISSUE TITLE
How to read zip files with wfs.readFile() ?

### ISSUE THREAD

**Issue by anoopemacs** [perry-mitchell/webdav-fs#32]
By default, it seems to work on some zip files and not on others.

To get around this, is it possible to read remote zip files without unzipping to a Buffer and then use some other tool to unzip the Buffer ?

**Comment by perry-mitchell** [comment]
There was a bug affecting `readFile` recently (#33), but it's been fixed in 0.7.1. Would you mind checking again to see if it works with every zip file?

When using `readFile` to fetch a remote zip file, you're returned the zip-file as-is (compressed). The buffer you receive is the zip data, which you can unzip using any tool you want or simply write it to a .zip file.

**Comment by perry-mitchell** [comment]
I'm closing the issue due to inactivity. If you feel that there's still an issue, please file a new one and we can look at it there.
