### ISSUE TITLE
Support for Nextcloud while in browser

### ISSUE THREAD

**Issue by mehi-shokri** [perry-mitchell/webdav-fs#52]
Thank's for providing this library.  
I'm curious if there is any browser side file explorer library for WebDAV (doesn't matter that it should use this library).  

Also since I don't want to open another issue I'm gonna ask another question here:  What's your strategy to connect to a Nextcloud WebDAV client which uses SSO for it's authentication?

**Comment by perry-mitchell** [comment]
Hi @mehrdaad - Thanks!

> I'm curious if there is any browser side file explorer library for WebDAV (doesn't matter that it should use this library).

I haven't used many, but for the [buttercup browser extension](https://github.com/buttercup/buttercup-browser-extension), I used [rc-tree](https://github.com/react-component/tree). It's not bad, but there's a bit of manual work mapping webdav results to the tree (not much though). There's also [react-folder-tree](https://github.com/procore/React-Folder-Tree) that I was looking at, but haven't used.

> What's your strategy to connect to a Nextcloud WebDAV client which uses SSO for it's authentication?

To be honest it's been some time since I tried Nextcloud on the client side. Last I remember there were frequent issues with CORS and other items Nextcloud feels is important. I primarily use ownCloud at home (ancestor product) which doesn't have these quirks, but I'll be spending some time on Nextcloud again soon in the browser extension for Buttercup, so I'll be debugging this product then.

**Comment by perry-mitchell** [comment]
If you don't mind, I'll update this issue to cover the CORS/SSO issue of working with nextcloud.

**Comment by mehrdaad** [comment]
@perry-mitchell sure! Will add my learnings too. Do you mind if I add topics related to integrating this lib with file explorer in this issue?  
Maybe we take this to the lib's wiki, but I suggest to keep this issue as a draft here.

**Comment by perry-mitchell** [comment]
If you find items that would make this library better, or have questions, it might be best to open a separate issue. The topics you brought up are clearly two different items and I don’t mind separate issues for that. I’m not sure that it’s the responsibility of this library to conform to any file manager libs (it should be the other way around).

I’m more than happy to discuss any questions or issues you have of course 👍

**Comment by perry-mitchell** [comment]
I'm going to close this issue as it's not the responsibility of this library to handle CORS issues or specific server integrations. While nextcloud has WebDAV support, it is [very faulty](https://github.com/nextcloud/server/issues/3131). If someone finds a workaround for it on the client side they can create a PR. I won't be accepting issues for Nextcloud unless they detail a bug in the code or some feature which would also benefit other users of this library. Hope you understand!

Please see the new [CORS notice](https://github.com/perry-mitchell/webdav-fs/blob/master/README.md#browser-usage-and-cors) in the readme.
