### ISSUE TITLE
Cant use readfile on image

### ISSUE THREAD

**Issue by nonoyek** [perry-mitchell/webdav-fs#70]
Is there anyway to read image file like jpg, png or others? I tried using '.txt' and it's worked perfectly, but when i change it to other file type it will show error.. is it possible to use utf8 to read image file? I tried using binary but the error show "fileReader.readAsArray not implemented".

**Comment by perry-mitchell** [comment]
Please see my [comment in the other issue](https://github.com/perry-mitchell/webdav-fs/issues/27#issuecomment-458697874).

**Comment by nonoyek** [comment]
I tried what u show me. I am actually using react-native to code. And in react-native there is no fileReader.readAsArray. Is there any other way i can solve this? Really worry about this, it's my assignment for this semester..

**Comment by perry-mitchell** [comment]
@nonoyek That's weird.. We're using webdav-client (the dependent of this library) in buttercup-mobile - a react native project. You can see [in our shim](https://github.com/buttercup/buttercup-mobile/blob/2314cc7995d7a1fd7d57637faabad0362792ce64/shim.js#L15) that we're using `buffer` to polyfill some functionality. I'm not aware of there being too much more.

I'd recommend using the latest [**webdav-client**](https://github.com/perry-mitchell/webdav-client) instead of this library if you're working on react-native.
